@uri=http://localhost:3005/auth


POST {{uri}}/login
Content-Type: application/json

{
  "username": "danielbelnuz18@gmail.com",
  "password": "test.123"
}

###
POST {{uri}}/refresh-token
Content-Type: application/json

{
 "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRhbmllbGJlbG51ejE4QGdtYWlsLmNvbSIsImlhdCI6MTcxMTgzMjY3MSwiZXhwIjoxNzExODMyOTcxfQ.rS31eWvUCqPZBHwz6cwzjwwCFZPLyND4uBRNDINUb4I"
}