@uri=http://localhost:3005/auth


POST {{uri}}/login
Content-Type: application/json

{
  "username": "danielbelnuz18@gmail.com",
  "password": "test.123"
}

###
POST {{uri}}/refresh-token
Content-Type: application/json

{
 "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiZmlyc3ROYW1lIjoiTWF0ZW8iLCJsYXN0TmFtZSI6IkJlbHRyYW4iLCJkb2NOdW1iZXIiOiIxMDA0MjcyMzgwIiwiZG9jdFR5cGUiOiJDQyIsImVtYWlsIjoiZGFuaWVsYmVsbnV6MThAZ21haWwuY29tIiwiaXNBY3RpdmUiOnRydWUsImlhdCI6MTcxMTgzMTQ3MSwiZXhwIjoxNzExODMxNzcxfQ.lfXv2Zq1HPfzQaSEtqYid1Kx3vMp0PrMUlYYQ6-AAA8ASD"
}