@uri=http://localhost:3005

GET {{uri}}/user
Content-Type: application/json

{
  "active": true
}

### get one
GET {{uri}}/user/4

###POST
POST {{uri}}/user
Content-Type: application/json

{
  "firstName": "Mateo",
  "lastName": "Beltran",
  "email": "danielbelnuz18@gmail.com",
  "password": "test.123",
  "docNumber": "1004272380",
  "docType": "CC"
}

### actualizar
PATCH {{uri}}/user/9
Content-Type: application/json

{
  "isActive": true
}


###
PUT {{uri}}/user/active/9